# Generated by Django 6.1.1 on 2026-10-08 17:06

import usuarios.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("usuario_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rol",
                    models.ForeignKey(
                        db_column="rol_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="usuarios",
                        to="usuarios.rol",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("correo", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("is_superuser", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
                "db_table": "usuarios",
                "managed": False,
            },
            managers=[
                ("objects", usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("rol_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "rol",
                "verbose_name_plural": "roles",
                "db_table": "roles",
                "managed": False,
            },
        ),
    ]
